### ISSUE TITLE
`XMLHTTPException: (MessageNotUnderstood) Message not understood: ZnLimitedReadStream >> #binary` encountered while executing `(XMLDOMParser parseURL: 'https://www.w3schools.com/xml/simple.xml') inspect`in Pharo 10

### ISSUE THREAD

**Issue by capsulecorplab** [pharo-contributions/XML-XMLParser#11]
![Screenshot from 2022-10-01 15-32-57](https://user-images.githubusercontent.com/14095576/193429198-41dd0714-2664-4e21-b5b6-4f50da91b6f5.png)

**Comment by JanBliznicenko** [comment]
It seems creating following method in ZnLimitedReadStream makes XMLParser to work in Pharo 10+:

```Smalltalk
binary
	stream binary
```

It could be added as an extension method, but I am not sure if I should create PR, as I do not understand ZnLimitedReadStream nor XMLParser enough to find any possible consequences.

@astares?

**Comment by astares** [comment]
One can provoke the issue using

```Smalltalk
(XMLDOMParser parseURL: 'https://www.w3schools.com/xml/simple.xml') inspect
```

(here in Pharo 11) and the stream is already a binary one when checking with #isBinary as it returns true.

So simply removing the #binary send should solve the issue.
