### ISSUE TITLE
Does not load into latest stable Pharo 12 x64 image on windows

### ISSUE THREAD

**Issue by riverdusty** [pharo-contributions/XML-XMLParser#38]
key 'XML-ParserGTExtensions' not found in Dictionary

![image](https://github.com/user-attachments/assets/da8e99e8-77eb-4d3d-98bd-3f66248b2c5e)

**Comment by astares** [comment]
Also it loads fine in CI for P12 and P13 and running tests are green

![image](https://github.com/user-attachments/assets/13682cf1-f4f9-4560-8bda-e7647a39c4ab)

So this does not seem to be an issue of the XML framework and it is hard to reproduce without further information.

@riverdusty 

1. Could you please give more infos on how you load?
2. Did you follow the load expression given on the project page?
3. Did you really start in a fresh image?
4. Are you sure you used a freshly downloaded clone of the repo (without any shared caching between images or other involved)

**Comment by riverdusty** [comment]
1. It loads fine in a truly fresh image. The image I was using had loaded svens xml-support before loading this xmlparser.
2. Yes, and was expecting any baselines to overwrite existing ones
3. No, the only thing loaded was svens xml-support, which apparently is the cause of this issue
4. Appears to be a conflict caused by the 2 xml repositories.

So its my fault this didn't work, but as a note, I would expect that loading this repo would overwrite a baseline, not attempt to use a baseline that doesn't belong to it.

**Comment by astares** [comment]
Hi @riverdusty 

if you talk about https://github.com/svenvc/XML-XMLParser then this is at the moment 47 commits
behind the formal one on https://github.com/pharo-contributions/XML-XMLParser - thats all I can see.

Anyhow - glad it is not a general problem and one argument more to always try in/use a fresh image
and work with reproducible builds.

I will close the issue.
