### ISSUE TITLE
Migrate GTExtensions package to NewTools

### ISSUE THREAD

**Issue by tinchodias** [pharo-contributions/XML-XMLParser#5]
The extension package is not trivial but we should have at least some basic tree of nodes in the Pharo 10 inspector.

**Comment by tinchodias** [comment]
I took a glance at the GTExtensions package and most of the code there seems to be not GT-related but a highlighter.

I tried how simple was to use that highlighter in a Pharo 10 and had this error: "XMLFileException: (XMLFileException) File reading unsupported"

To reproduce:
1. Load default metacello in P10.
2. Manually load the package using Iceberg.
3. Evaluate:
```
xmlFileReference := 'test.xml' asFileReference.
xmlFileReference writeStreamDo: [ :aStream |
	aStream nextPutAll:
		'<?xml version="1.0" encoding="UTF-8"?>
	<countries>
	  <country code="af" handle="afghanistan" continent="asia" iso="4">Afghanistan</country>
	  <country code="al" handle="albania" continent="europe" iso="8">Albania</country>
	  <country code="dz" handle="algeria" continent="africa" iso="12">Algeria</country>
	</countries>' ].

xmlFileHandle := XMLFileSystemFileHandle fileReference: xmlFileReference.

(XMLExternalDocumentConverter convertFileNamed: xmlFileHandle path)
```

**Comment by tinchodias** [comment]
And I forgot the say that the cause it that the `XMLExternalDocumentConverter` uses `XMLFileReadStreamFactory` which tries to find `StandardFileStream`

**Comment by astares** [comment]
@tinchodias where is XMLExternalDocumentConverter from?

**Comment by astares** [comment]
I introduced a new package "XML-Parser-Tools" using 

- Spec tree presenter to show the tree of nodes
- Spec table presenter to show attributes
- Spec text presenter to show the source contents

![image](https://github.com/pharo-contributions/XML-XMLParser/assets/5980033/5848af97-1323-433f-b45c-9e7d0c60a4db)

![image](https://github.com/pharo-contributions/XML-XMLParser/assets/5980033/0286d1f6-c857-4b36-903a-71fe1833ca91)
